version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.9 /usr/local/share/virtualenvs/tap-ga360
            source /usr/local/share/virtualenvs/tap-ga360/bin/activate
            uv pip install -U pip setuptools
            uv pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-ga360/bin/activate
            pylint tap_ga360 --disable missing-function-docstring,missing-class-docstring,missing-module-docstring,too-many-locals,invalid-name,line-too-long,consider-using-f-string,unspecified-encoding,use-yield-from

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
